// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StefaniniPracticalTest.Data.Context;

namespace StefaniniPracticalTest.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210419023937_DataSeed")]
    partial class DataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StefaniniPracticalTest.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Porto Alegre",
                            RegionId = 1
                        });
                });

            modelBuilder.Entity("StefaniniPracticalTest.Domain.Entities.Classification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Classifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "VIP"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Regular"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sporadic"
                        });
                });

            modelBuilder.Entity("StefaniniPracticalTest.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("ClassificationId")
                        .HasColumnType("int");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastPurchase")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ClassificationId");

                    b.HasIndex("GenderId");

                    b.HasIndex("RegionId");

                    b.HasIndex("UserId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            ClassificationId = 1,
                            GenderId = 1,
                            LastPurchase = new DateTime(2016, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maurício",
                            Phone = "(11) 95429999",
                            RegionId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            ClassificationId = 1,
                            GenderId = 2,
                            LastPurchase = new DateTime(2015, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Carla",
                            Phone = "(53) 94569999",
                            RegionId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            ClassificationId = 3,
                            GenderId = 2,
                            LastPurchase = new DateTime(2013, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maria",
                            Phone = "(64) 94518888",
                            RegionId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CityId = 1,
                            ClassificationId = 2,
                            GenderId = 1,
                            LastPurchase = new DateTime(2016, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Douglas",
                            Phone = "(51) 12455555",
                            RegionId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            CityId = 1,
                            ClassificationId = 2,
                            GenderId = 2,
                            LastPurchase = new DateTime(2016, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marta",
                            Phone = "(51) 45788888",
                            RegionId = 1,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("StefaniniPracticalTest.Domain.Entities.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Masculine"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Feminine"
                        });
                });

            modelBuilder.Entity("StefaniniPracticalTest.Domain.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rio Grande do Sul"
                        },
                        new
                        {
                            Id = 2,
                            Name = "São Paulo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Curitiba"
                        });
                });

            modelBuilder.Entity("StefaniniPracticalTest.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAdmin = true,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            IsAdmin = false,
                            Name = "Seller "
                        });
                });

            modelBuilder.Entity("StefaniniPracticalTest.Domain.Entities.UserSys", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserRoleId");

                    b.ToTable("UserSys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@app.com",
                            Login = "Administrator",
                            Password = "e6e061838856bf47e1de730719fb2609",
                            UserRoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "seller1@app.com",
                            Login = "Seller1",
                            Password = "15a0185323e401148285d087185cb6c8",
                            UserRoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "seller2@app.com",
                            Login = "Seller2",
                            Password = "cfd6fa9b293a147327cc92af0ce3eeb0",
                            UserRoleId = 2
                        });
                });

            modelBuilder.Entity("StefaniniPracticalTest.Domain.Entities.City", b =>
                {
                    b.HasOne("StefaniniPracticalTest.Domain.Entities.Region", "Region")
                        .WithMany("Cities")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("StefaniniPracticalTest.Domain.Entities.Customer", b =>
                {
                    b.HasOne("StefaniniPracticalTest.Domain.Entities.City", "City")
                        .WithMany("Customers")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StefaniniPracticalTest.Domain.Entities.Classification", "Classification")
                        .WithMany("Customers")
                        .HasForeignKey("ClassificationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StefaniniPracticalTest.Domain.Entities.Gender", "Gender")
                        .WithMany("Customers")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StefaniniPracticalTest.Domain.Entities.Region", "Region")
                        .WithMany("Customers")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StefaniniPracticalTest.Domain.Entities.UserSys", "User")
                        .WithMany("Customers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Classification");

                    b.Navigation("Gender");

                    b.Navigation("Region");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StefaniniPracticalTest.Domain.Entities.UserSys", b =>
                {
                    b.HasOne("StefaniniPracticalTest.Domain.Entities.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("StefaniniPracticalTest.Domain.Entities.City", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("StefaniniPracticalTest.Domain.Entities.Classification", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("StefaniniPracticalTest.Domain.Entities.Gender", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("StefaniniPracticalTest.Domain.Entities.Region", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("StefaniniPracticalTest.Domain.Entities.UserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("StefaniniPracticalTest.Domain.Entities.UserSys", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
